### ISSUE TITLE
Issues with Automatic Installation

### ISSUE THREAD

**Issue by allyrancourt** [GhidraJupyter/ghidra-jupyter-kotlin#3]
It seems as though there is some deprecated code when extension is installed via the automatic method; I got an error saying that the DockingAction method setEnabled didn't exist and it looks to be because the function signature changed in a recent version of Ghidra.

Installing manually by downloading the release zip and putting that in the extensions folder, on the other hand, worked fine.

**Comment by fmagin** [comment]
I think this is the same (or related) as #1 
Did you use the automatic install with a Ghidra 9.1.2 or 9.2 install? the signature of `setEnabled` changed in version 9.2, so there is one precompiled release of the plugin for 9.1.2 and one for 9.2. The automatic installer assumes the latest version, so it installs the release for 9.2, which will not work for 9.1.2 or earlier

**Comment by fmagin** [comment]
Closing this because I am confident enough that this is the same issue as #1 which was fixed already
